#
# Oracle Java 8 Dockerfile
#
# https://github.com/dockerfile/java
# https://github.com/dockerfile/java/tree/master/oracle-java8
#

# Pull base image.
FROM cyloon-crawler
WORKDIR /data
ADD . /data/
RUN ls
# Define commonly used JAVA_HOME variable
CMD ["/data/crawler.sh"]

